USE [master]
GO
/****** Object:  Database [FindMyTherapist]    Script Date: 2/8/2019 7:07:12 PM ******/
CREATE DATABASE [FindMyTherapist]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FindMyTherapist', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FindMyTherapist.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FindMyTherapist_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FindMyTherapist_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [FindMyTherapist] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FindMyTherapist].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FindMyTherapist] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FindMyTherapist] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FindMyTherapist] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FindMyTherapist] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FindMyTherapist] SET ARITHABORT OFF 
GO
ALTER DATABASE [FindMyTherapist] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FindMyTherapist] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FindMyTherapist] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FindMyTherapist] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FindMyTherapist] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FindMyTherapist] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FindMyTherapist] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FindMyTherapist] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FindMyTherapist] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FindMyTherapist] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FindMyTherapist] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FindMyTherapist] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FindMyTherapist] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FindMyTherapist] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FindMyTherapist] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FindMyTherapist] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FindMyTherapist] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FindMyTherapist] SET RECOVERY FULL 
GO
ALTER DATABASE [FindMyTherapist] SET  MULTI_USER 
GO
ALTER DATABASE [FindMyTherapist] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FindMyTherapist] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FindMyTherapist] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FindMyTherapist] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FindMyTherapist] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'FindMyTherapist', N'ON'
GO
ALTER DATABASE [FindMyTherapist] SET QUERY_STORE = OFF
GO
USE [FindMyTherapist]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [FindMyTherapist]
GO
/****** Object:  Table [dbo].[FavTherapist]    Script Date: 2/8/2019 7:07:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FavTherapist](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[userId] [int] NULL,
	[therapistId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reviews]    Script Date: 2/8/2019 7:07:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reviews](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[therapistId] [int] NULL,
	[review] [varchar](255) NULL,
	[rating] [int] NULL,
	[userId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SavedTherapist]    Script Date: 2/8/2019 7:07:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SavedTherapist](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[userId] [int] NULL,
	[therapistId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Therapists]    Script Date: 2/8/2019 7:07:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Therapists](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[firstname] [varchar](255) NULL,
	[lastname] [varchar](255) NULL,
	[img] [varchar](255) NULL,
	[specialty] [varchar](255) NULL,
	[address] [varchar](255) NULL,
	[city] [varchar](255) NULL,
	[state] [varchar](255) NULL,
	[zip] [int] NULL,
	[phone] [bigint] NULL,
	[web] [varchar](255) NULL,
	[userId] [int] NULL,
	[savedId] [int] NULL,
	[favId] [int] NULL,
	[reviewId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 2/8/2019 7:07:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[firstname] [varchar](255) NULL,
	[lastname] [varchar](255) NULL,
	[address] [varchar](255) NULL,
	[city] [varchar](255) NULL,
	[state] [varchar](255) NULL,
	[zip] [int] NULL,
	[email] [varchar](255) NULL,
	[therapistId] [int] NULL,
	[savedId] [int] NULL,
	[favId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Reviews]  WITH CHECK ADD FOREIGN KEY([userId])
REFERENCES [dbo].[Users] ([id])
GO
ALTER TABLE [dbo].[Therapists]  WITH CHECK ADD FOREIGN KEY([favId])
REFERENCES [dbo].[FavTherapist] ([id])
GO
ALTER TABLE [dbo].[Therapists]  WITH CHECK ADD FOREIGN KEY([reviewId])
REFERENCES [dbo].[Reviews] ([id])
GO
ALTER TABLE [dbo].[Therapists]  WITH CHECK ADD FOREIGN KEY([savedId])
REFERENCES [dbo].[SavedTherapist] ([id])
GO
ALTER TABLE [dbo].[Therapists]  WITH CHECK ADD FOREIGN KEY([userId])
REFERENCES [dbo].[Users] ([id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([favId])
REFERENCES [dbo].[FavTherapist] ([id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([savedId])
REFERENCES [dbo].[SavedTherapist] ([id])
GO
USE [master]
GO
ALTER DATABASE [FindMyTherapist] SET  READ_WRITE 
GO
